### ISSUE TITLE
Crashes after generating dungeon

### ISSUE THREAD

**Issue by kaimokene** [TheMarstonConnell/Crawler#1]
Hello. I assume it is ur mod issue since ur dungeon was generated at same second these errors started appearing [23:02:53] [Server thread/INFO]: [com.mic.dungeonmod.util.world.DungeonGenerator$1Dungeon:generateDungeon:255]: Generating a dungeon at BlockPos{x=522, y=43, z=14}...
[23:02:53] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@95a1f58:
java.lang.StackOverflowError: null
	at net.minecraft.block.BlockChest.checkForSurroundingChests(BlockChest.java:177) ~[api.class:?]
	at net.minecraft.block.BlockChest.onBlockAdded(BlockChest.java:98) ~[api.class:?]
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:614) ~[axw.class:?]
	at net.minecraft.world.World.setBlockState(World.java:343) ~[amu.class:?] it spammed this in console alot and then finally crashed.

**Comment by ghost** [comment]
I just made a forge minecraft server, removed all mods except crawler, deleted world, and still the server crashes before even making a world.

Are you running a server or is this solo? Because if it's server then I think this mod just bricks everything if put on a server.

Edit: My issue is different from yours actually I just realized, since my issue is Exception in server tick loop and this happens before the world even starts generating. So I was wondering how you got the mod to run AT ALL on a server (If you are running this on a server that is)

**Comment by kaimokene** [comment]
Im 100% certain i was running it on single player.
